dist: xenial
language: ruby
rvm: "2.5.3"
cache: bundler
sudo: false

git:
  depth: 1
  submodules: false

env:
  - JEKYLL_ENV=production LC_ALL=C.UTF-8

before_script:
  - script/prepare.sh

script:
  # 'if [ $TRAVIS_EVENT_TYPE = cron ]; then bundle exec jekyll algolia; fi'
  - bundle exec jekyll build --profile --trace

after_success:
  - script/patch.sh
  - script/deploy-travis.sh
