name: algolia

on:
  schedule:
    - cron: '7 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup cache for Bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-2.7-${{ hashFiles('Gemfile') }}
    - name: Install dependencies
      run: bundle install --path=vendor/bundle
    - name: Update Algolia index
      run: bundle exec jekyll algolia push --trace
