name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_KEY_E: ${{ secrets.SSH_KEY_E }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup cache for Bundler
      id: cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundler-2.7-${{ hashFiles('Gemfile') }}
    - name: Install dependencies
      run: bundle install --path=vendor/bundle
    - name: Prepare build
      run: bash script/prepare.sh
    - name: Build site
      run: bundle exec jekyll build --trace --profile
      env:
        JEKYLL_ENV: production
        RUBYOPT: -W0
    - name: Post-build patches
      run: bash script/patch.sh
    - name: Deploy to GitHub
      run: bash script/deploy-actions.sh

    - uses: actions/setup-node@v1
    - name: Setup cache for Node.js
      id: cache-npm
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-20200427
    - name: Install Netlify CLI
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install netlify-cli
    - name: Deploy to Netlify
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      run: |
        git clone --depth=1 --single-branch https://github.com/iBug/image.git _site/image/
        rm -rf _site/image/.git
        npx netlify deploy --prod
