name: build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_KEY_E: ${{ secrets.SSH_KEY_E }}
      LSI: 'true'
      TZ: Etc/UTC
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup cache for Bundler
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          Gemfile.lock
          vendor/bundle
        key: ${{ runner.os }}-bundler-2-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-bundler-2-

    - uses: actions/setup-node@v1
    - name: Setup cache for Node.js
      id: cache-npm
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install - System
      run: sudo apt-get -y install libgsl-dev

    - name: Install - Bundler
      run: |
        bundle install --path=vendor/bundle
        bundle clean

    - name: Install - NPM
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: |
        npm install --also=dev
        npm prune

    - name: Prepare build
      run: bash script/prepare.sh
    - name: Build site
      run: bundle exec jekyll build --trace --profile --lsi --future
      env:
        JEKYLL_ENV: production
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Algolia index
      run: bundle exec jekyll algolia push
      env:
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      continue-on-error: true
    - name: Post-build patches
      run: bash script/patch.sh

    - name: Deploy to GitHub
      run: script/deploy-actions.sh

    - name: Deploy to Netlify
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      run: script/deploy-netlify.sh
